# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
    build:
        macos:
            xcode: "10.1.0"
        environment:
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8
        shell: /bin/bash --login -eo pipefail
        steps:
            - checkout
